Update buildspec.yaml

diff --git a/buildspec.yaml b/buildspec.yaml
--- a/buildspec.yaml
+++ b/buildspec.yaml
@@ -11,7 +11,7 @@ phases:
     runtime-versions:
       java: corretto11
     commands:
-      - "echo Checking AWS CLI and Docker versions"
+      - "echo Installing prerequisites"
       - "aws --version"
       - "docker --version"
       - "echo Logging into ECR"
@@ -19,30 +19,27 @@ phases:
 
   pre_build:
     commands:
-      - |
-        echo "Building Spring Boot JAR"
-        set -o pipefail
-        mvn -X clean package -DskipTests | tee build.log
-        MAVEN_EXIT=${PIPESTATUS[0]}
-        echo "Packaging complete (status: $MAVEN_EXIT)"
-        if [ $MAVEN_EXIT -ne 0 ]; then
-          echo "Maven build failed, see build.log for details"
-          exit $MAVEN_EXIT
-        fi
-      - |
-        echo "Building and pushing Docker image"
-        IMAGE_TAG=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
-        docker build -t "$IMAGE_TAG" .
-        docker tag "$IMAGE_TAG" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest"
-        docker push "$IMAGE_TAG"
-        docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest"
+      - "echo Preparing build environment"
+      - "echo Source version: $CODEBUILD_RESOLVED_SOURCE_VERSION"
+
+  build:
+    commands:
+      - "echo Building Spring Boot JAR..."
+      - "set -o pipefail"
+      - "mvn -X clean package -DskipTests | tee build.log"
+      - "MAVEN_EXIT=${PIPESTATUS[0]}"
+      - "if [ $MAVEN_EXIT -ne 0 ]; then echo 'Maven build failed (code: '$MAVEN_EXIT')'; exit $MAVEN_EXIT; fi"
+      - "echo Building Docker image..."
+      - "IMAGE_TAG=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION"
+      - "docker build -t $IMAGE_TAG ."
+      - "docker tag $IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest"
+      - "docker push $IMAGE_TAG"
+      - "docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest"
 
   post_build:
     commands:
       - "echo Build completed on $(date)"
-      - "echo Image URIs:"
-      - "echo $IMAGE_TAG"
-      - "echo $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest"
+      - "echo Pushed image tags: $IMAGE_TAG and $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest"
 
 artifacts:
   files:
